apiVersion: v1
kind: Service
metadata:
  name: silversea-mgmt-service  # Name of the service
spec:
  type: NodePort  # Exposes the service on a port on each node, making it accessible externally
  selector:
    app: silversea-mgmt  # Selects the pods with this label to route traffic to
  ports:
    - protocol: TCP        # Protocol used by the service
      port: 5050           # External port for the service; use 5050 for Minikube, 80 can be used in production for standard HTTP
      targetPort: 5050     # Port on the container to forward traffic to
      nodePort: 31000      # Fixed external port on the node (range: 30000â€“32767) 